### ISSUE TITLE
Profile

### ISSUE THREAD

**Issue by aksiooma** [kridesav/Helip#68]
**Kaikki mikä liittyy Käyttäjien Profiiliin.**
- FireStore/Firebase integrointi
- Oman profiilin näkymä johon tiedot haetaan firebasesta.

**Ehdotuksia:**
-Edit profile: Etunimi, Sukunimi, Display_name, Kuvaus, Kuva
-Add profile image? (tallentuuko firestorageen?)
-Käyttäjä eventtien määrän numerona (ilmoittautunut, luonut)

**Completed:**
-Firestore integrointi tehty.
-Collection sisältää seuraavia fieldejä: FirstName, LastName, DisplayName, UsedID, EventsParticipating, EventsCreated, Email, ProfileImageURL,

Tehtävä:
-Subscreens: asetukset, groups (ei ehditä)
-DisplayName:n muuttaminen.
-Salasanan muuttaminen.

**HUOM: voidaan irroittaa omiksi todo-taskeiksi.**

**Comment by kridesav** [comment]
Pilkottu pienempii osiin; closing.
