### ISSUE TITLE
Lokaatioiden sorttaus etäisyyden perusteella

### ISSUE THREAD

**Issue by Tukkis** [kridesav/Helip#75]
ETA: 60min
Tehdään alustavasti frontissa fetchin yhteydessä

**Comment by Tukkis** [comment]
ETA: 60min
Tehdään alustavasti frontissa fetchin yhteydessä

**Comment by kridesav** [comment]
Sortin yhteyteen lisätty että lisää jokaiselle paikalle myös distance valuen mitä voi käyttää hyväksi kaikkialla.
